ARG PACKAGE=blob-aggregator

FROM --platform=$BUILDPLATFORM golang:1.23.0 AS builder

ARG PACKAGE

RUN apt install git curl

RUN mkdir /taiko-mono

WORKDIR /taiko-mono

COPY . .

RUN go mod download

WORKDIR /taiko-mono/packages/${PACKAGE}

RUN GOOS=linux go build -o /taiko-mono/packages/${PACKAGE}/bin/${PACKAGE} /taiko-mono/packages/${PACKAGE}/cmd/main.go

FROM debian:bookworm-slim

ARG PACKAGE
ENV PACKAGE=${PACKAGE}

RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates

COPY --from=builder /taiko-mono/packages/${PACKAGE}/bin/${PACKAGE} /usr/local/bin/

ENTRYPOINT ["/usr/local/bin/${PACKAGE}"]
