services:
  bridge-ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    volumes:
      - ./config:/app/config
    # Only build and start when explicitly requested
    profiles:
      - bridge-ui
