services:
  bridge-ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bridge-ui
    ports:
      - "3000:3000"
    # volumes:
    #   - ./config:/app/config
    # Only build and start when explicitly requested
    profiles:
      - bridge-ui
    networks:
      - app-network

  nginx:
    image: nginx:latest
    # build:
    #   context: .
    #   dockerfile: nginx/Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    profiles:
      - nginx
    networks:
      - app-network
    volumes:
      - ./packages/bridge-ui/nginx/ssl:/etc/nginx/ssl:ro
      - ./packages/bridge-ui/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  app-network:
    driver: bridge
