services:
  db:
    image: mysql:8.0
    container_name: "db"
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=relayer
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - rabbitmq_go_net
    profiles:
      - init

  migrations:
    image: ghcr.io/kukymbr/goose-docker:3.22.1
    environment:
      - GOOSE_DRIVER=mysql
      - GOOSE_DBSTRING=root:root@tcp(db:3306)/relayer
    volumes:
      - ./migrations:/migrations
    networks:
      - rabbitmq_go_net
    profiles:
      - migrations

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net
    profiles:
      - init

  relayer-processor:
    image: nethsurge/taiko-relayer:latest
    container_name: relayer-processor
    restart: always
    entrypoint: ["/usr/local/bin/relayer"]
    ports:
      - 6061:6061
    command:
      - processor
      - --db.host=db
      - --db.maxIdleConns=50
      - --db.maxOpenConns=3000
      - --db.name=relayer
      - --db.password=root
      - --db.username=root
      - --destBridgeAddress=0x1670000000000000000000000000000000000001
      - --destRpcUrl=ws://185.3.95.99:8548
      - --confirmations=2
      - --destERC1155Address=0x1670000000000000000000000000000000000004
      - --destERC20VaultAddress=0x1670000000000000000000000000000000000002
      - --destERC721Address=0x1670000000000000000000000000000000000003
      - --destTaikoAddress=0x1670000000000000000000000000000000010001
      - --processorPrivateKey=39725efee3fb28614de3bacaffe4cc4bd8c436257e2c8bb887c4b5c4be45e76d
      - --srcRpcUrl=ws://185.3.95.99:32003
      - --srcSignalServiceAddress=0x00c042C4D5D913277CE16611a2ce6e9003554aD5
      - --headerSyncInterval=2
      - --queue.host=rabbitmq
      - --queue.password=root
      - --queue.port=5672
      - --queue.username=root
    networks:
      - rabbitmq_go_net
    profiles:
      - relayer

  relayer-indexer:
    image: nethsurge/taiko-relayer:latest
    container_name: relayer-indexer
    restart: always
    entrypoint: ["/usr/local/bin/relayer"]
    ports:
      - 6062:6062
    command:
      - indexer
      - --db.host=db
      - --db.connMaxLifetime=100000
      - --db.maxIdleConns=50
      - --db.maxOpenConns=3000
      - --db.name=relayer
      - --db.password=root
      - --db.username=root
      - --destBridgeAddress=0x1670000000000000000000000000000000000001
      - --destRpcUrl=ws://185.3.95.99:8548
      - --metrics.port=6062
      - --queue.host=rabbitmq
      - --queue.password=root
      - --queue.port=5672
      - --queue.username=root
      - --srcRpcUrl=ws://185.3.95.99:32003
      - --srcSignalServiceAddress=0x00c042C4D5D913277CE16611a2ce6e9003554aD5
      - --blockBatchSize=100
      - --event=MessageSent
      - --maxNumGoroutines=50
      - --srcBridgeAddress=0x72bCbB3f339aF622c28a26488Eed9097a2977404
      - --srcTaikoAddress=0xaE37C7A711bcab9B0f8655a97B738d6ccaB6560B
    networks:
      - rabbitmq_go_net
    profiles:
      - relayer

  relayer-api:
    image: nethsurge/taiko-relayer:latest
    container_name: relayer-api
    restart: always
    entrypoint: ["/usr/local/bin/relayer"]
    ports:
      - 4102:4102
    command:
      - api
      - --db.host=db
      - --db.connMaxLifetime=100000
      - --db.maxIdleConns=50
      - --db.maxOpenConns=3000
      - --db.name=relayer
      - --db.password=root
      - --db.username=root
      - --destRpcUrl=ws://185.3.95.99:8548
      - --destTaikoAddress=0x1670000000000000000000000000000000010001
      - --srcRpcUrl=ws://185.3.95.99:32003
    networks:
      - rabbitmq_go_net
    profiles:
      - relayer

volumes:
  mysql_data:
    driver: local

networks:
  rabbitmq_go_net:
    driver: bridge
