name: "[Nethermind] Taiko Protocol - Docker build and push"

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - "packages/protocol/**"
      - ".github/workflows/taiko-protocol--docker-build.yml"
  push:
    branches: [main]
    tags:
      - "taiko-protocol-v*"
    paths:
      - "packages/protocol/**"
      - ".github/workflows/taiko-protocol--docker-build.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  attestations: write
  contents: read

jobs:
  build:
    uses: NethermindEth/github-workflows/.github/workflows/docker-build-push-dockerhub.yaml@v1.3.4
    with:
      image_name: taiko-protocol
      platforms: "linux/amd64,linux/arm64"
      context: "packages/protocol"
      dockerfile_path: "packages/protocol/Dockerfile"
      push: ${{ github.event_name != 'pull_request' }}
      ignore_trivy: true # TODO: remove this once security issues are fixed
    secrets:
      dockerhub_username: ${{ secrets.DOCKER_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKER_PASSWORD }}
